### ISSUE TITLE
Implement Federation endpoints

### ISSUE THREAD

**Issue by lenguyenthanh** [lenguyenthanh/fide#37]
Build upon what We have [here](https://github.com/lenguyenthanh/fide/blob/main/modules/smithy/src/main/smithy/federations.smithy) to provide the current experience (and more) We have in [lichess](https://lichess.org/fide/federation)

- [x] Design new Database schema, migration scripts if needed
- [x] Write SQL query
- [x] Update smithy specification
- [x] wire everything together in `service.federation.scala` similar to [service.player.scala](https://github.com/lenguyenthanh/fide/blob/main/modules/backend/src/main/scala/service.player.scala)
- [x] Some tests maybe
